-- MySQL Script generated by MySQL Workbench
-- Sun Apr 25 14:55:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NULL,
  `userPassword` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `categoryname` VARCHAR(45) NULL,
  `categorydesconto` FLOAT NULL,
  PRIMARY KEY (`idcategory`),
  UNIQUE INDEX `idcategory_UNIQUE` (`idcategory` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produt` (
  `idprodut` INT NOT NULL AUTO_INCREMENT,
  `nameProdut` VARCHAR(45) NOT NULL,
  `priceProdut` FLOAT NOT NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`idprodut`),
  INDEX `fk_produt_category1_idx` (`category_idcategory` ASC) VISIBLE,
  CONSTRAINT `fk_produt_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `mydb`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `idorder` INT NOT NULL AUTO_INCREMENT,
  `i` VARCHAR(45) NULL,
  `produt_idprodut` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idorder`, `produt_idprodut`),
  INDEX `fk_order_produt_idx` (`produt_idprodut` ASC) VISIBLE,
  INDEX `fk_order_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_order_produt`
    FOREIGN KEY (`produt_idprodut`)
    REFERENCES `mydb`.`produt` (`idprodut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`discountOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`discountOrder` (
  `iddiscountOrder` INT NOT NULL AUTO_INCREMENT,
  `discountOrderValue` DECIMAL NULL,
  PRIMARY KEY (`iddiscountOrder`),
  UNIQUE INDEX `iddiscountOrder_UNIQUE` (`iddiscountOrder` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
